### ISSUE TITLE
java.lang.NoSuchMethodError kotlinx.serialization.json.Json.stringify

### ISSUE THREAD

**Issue by hamadycisse** [JetBrains/kotless#94]
Hello 

After upgrading to v0.1.7-beta-5, my integrated test (using Kotest) fail:

```
java.lang.NoSuchMethodError: kotlinx.serialization.json.Json.stringify(Lkotlinx/serialization/SerializationStrategy;Ljava/lang/Object;)Ljava/lang/String;
	at io.kotless.local.handler.DynamicHandler.handle(DynamicHandler.kt:75)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
It works when I run the server locally.

**Comment by hamadycisse** [comment]
I was able to solve it by specifying the right version in my test compile:
`testRuntimeOnly("io.kotless:kotless-lang-local:$kotlessVersion")`
